gadgetlikelihood('likelihood', gd$dir, missingOkay=T) %>%
    gadget_update('penalty',
                  name = "bounds",
                  weight = "0.5",
                  data = data.frame(
                      switch = c("default"),
                      power = c(2),
                      upperW=10000,
                      lowerW=10000,
                      stringsAsFactors = FALSE)) %>%
    gadget_update('understocking',
                  name = 'understocking',
                  weight = '100') %>%
    gadget_update('catchdistribution',
                  name = 'ldist.spr',
                  weight = 1,
                  data = ldist.spr,
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.spr',
                  weight = 1,
                  data = aldist.spr,
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.aut',
                  weight = 1,
                  data = ldist.aut,
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.aut',
                  weight = 1,
                  data = aldist.aut,
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.comm',
                  weight = 1,
                  data = ldist.catch,
                  fleetnames = c('comm'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.comm',
                  weight = 1,
                  data = aldist.catch,
                  fleetnames = c('comm'),
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.short',
                  weight = 1,
                  data = spr.si.short,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.mid',
                  weight = 1,
                  data = spr.si.mid,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.long',
                  weight = 1,
                  data = spr.si.long,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.short',
                  weight = 1,
                  data = aut.si.short,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.mid',
                  weight = 1,
                  data = aut.si.mid,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.long',
                  weight = 1,
                  data = aut.si.long,
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    write.gadget.file(gd$dir)
