---
title: "Gadget-Atlantis Haddock Model"
author: "Paul Frater"
date: "February 14, 2017"
output: html_document
---
```{r global_options, include=F}
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=F, warning=F, message=F)
knitr::opts_knit$set(root.dir = '~/gadget/models/atlantis/haddock/hadVersions')
```


# -----------------------------------------------------------------------------------



# Tracer Model - fixed mortality only
```{r, mod26 gadget results, include=F}
library(plyr)
library(dplyr)
library(ggplot2)
library(grid)
library(Rgadget)
fit <- read.table('hadMod26/out.fit/had.std', comment.char = ';')
names(fit) <- c('year', 'step', 'area', 'age', 'number', 'mean.length', 'mean.weight',
                'stddev.length', 'number.consumed', 'biomass.consumed')

fit.biomass <- 
    fit %>%
    mutate(biomass = number * mean.weight) %>%
    group_by(year) %>%
    summarize(annual.biomass = sum(biomass))
    
fit.numbers <- 
    fit %>%
    group_by(year) %>%
    summarize(ann.number = sum(number))

age.numbers <- 
    fit %>%
    mutate(age = age - (age %% 2)) %>%
    group_by(year, age) %>%
    summarize(ann.number = sum(number))
```

```{r, atlantis results, include=F}
library(tidyr)
library(mfdb)
library(mfdbatlantis)
library(utils)
library(magrittr)
is_dir <- atlantis_directory('~/Dropbox/Paul_IA/OutM45BioV158FMV79_PF')

is_run_options <- atlantis_run_options(is_dir)

# Read in areas / surface temperatures, insert into mfdb
is_area_data <- atlantis_read_areas(is_dir)
is_temp <- atlantis_temperature(is_dir, is_area_data)

# Read in all functional groups, assign MFDB shortcodes where possible
is_functional_groups <- atlantis_functional_groups(is_dir)
is_functional_groups$MfdbCode <- vapply(
    mfdb_find_species(is_functional_groups$LongName)['name',],
    function (x) if (length(x) > 0) x[[1]] else as.character(NA), "")

# assemble and import haddock 
fgName <- 'Haddock'
fg_group <- is_functional_groups[c(is_functional_groups$Name == fgName),]
is_fg_count <- atlantis_fg_tracer(is_dir, is_area_data, fg_group)


# compare biomass by year in gadget to atlantis
atl.biomass <- 
    read.table('~/Dropbox/Paul_IA/OutM45BioV158FMV79_PF/OutBiomIndx.txt', 
                          header=T) %>%
    mutate(year = 1948:2013) %>%
    select(year, starts_with(fg_group$GroupCode)) %>%
    mutate(atl.biomass = FHA*1000)
```

```{r, gadget-atlantis mod26, comp, include=F}
# plot gadget biomass against atlantis
atl.gad.biomass <- left_join(fit.biomass, atl.biomass)

atl.gad.plot <- 
    ggplot(data=atl.gad.biomass, aes(x=atl.biomass, y=annual.biomass)) + geom_point() +
    geom_abline(intercept=0, slope=1) + theme_bw() + 
    xlab('Atlantis Annual Biomass') + ylab('Gadget Annual Biomass')

atl.gad.ts <-
    ggplot(data=atl.gad.biomass, aes(x=year)) + 
    geom_line(aes(y=annual.biomass, color='Gadget')) +
    geom_line(aes(y=atl.biomass, color='Atlantis')) + 
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Biomass')



#######################################
## to check numbers instead of biomass
#######################################
had.numbers <- 
    is_fg_count %>% 
    filter(month == 2) %>%
    group_by(year) %>% 
    summarize(atl.number = sum(count))
atl.gad.numbers <- left_join(fit.numbers, had.numbers)

had.numbers.plot <- 
    ggplot(data=atl.gad.numbers, aes(x=year)) + 
    geom_line(aes(y=ann.number, color='Gadget')) +
    geom_line(aes(y=atl.number, color='Atlantis')) +
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Numbers')

atl.age.numbers <- 
    is_fg_count %>%
    filter(month == 1) %>%
    group_by(year, age) %>%
    summarize(atl.number = sum(count))

age.numbers.plot <- 
    ggplot(data=age.numbers, aes(x=year, y=ann.number, color='Gadget')) + geom_line() +
    geom_line(data=atl.age.numbers, aes(x=year, y=atl.number, color='Atlantis')) +
    facet_wrap(~age) +
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Numbers')
```

## Biomass Across Time
```{r, mod26 biomass plot}
atl.gad.ts + ylim(0,1e+09)
```

## Numbers Across Time
```{r, mod26 numbers plot}
had.numbers.plot
```

## Numbers by Age Across Time
```{r, mod26 numbers by age plot}
age.numbers.plot
```



#------------------------------------------------------------------------------------

# Tracer Model - fixed mortality, selectivity, and growth
```{r, mod24 gadget results, include=F}
library(plyr)
library(dplyr)
library(ggplot2)
library(grid)
library(Rgadget)
fit <- read.table('hadMod24/out.fit/had.std', comment.char = ';')
names(fit) <- c('year', 'step', 'area', 'age', 'number', 'mean.length', 'mean.weight',
                'stddev.length', 'number.consumed', 'biomass.consumed')

fit.biomass <- 
    fit %>%
    mutate(biomass = number * mean.weight) %>%
    group_by(year) %>%
    summarize(annual.biomass = sum(biomass))
    
fit.numbers <- 
    fit %>%
    group_by(year) %>%
    summarize(ann.number = sum(number))

age.numbers <- 
    fit %>%
    mutate(age = age - (age %% 2)) %>%
    group_by(year, age) %>%
    summarize(ann.number = sum(number))
```


```{r, mod24 gadget-atlantis comp, include=F}
# plot gadget biomass against atlantis
atl.gad.biomass <- left_join(fit.biomass, atl.biomass)

atl.gad.plot <- 
    ggplot(data=atl.gad.biomass, aes(x=atl.biomass, y=annual.biomass)) + geom_point() +
    geom_abline(intercept=0, slope=1) + theme_bw() + 
    xlab('Atlantis Annual Biomass') + ylab('Gadget Annual Biomass')

atl.gad.ts <-
    ggplot(data=atl.gad.biomass, aes(x=year)) + 
    geom_line(aes(y=annual.biomass, color='Gadget')) +
    geom_line(aes(y=atl.biomass, color='Atlantis')) + 
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Biomass')



#######################################
## to check numbers instead of biomass
#######################################
had.numbers <- 
    is_fg_count %>% 
    filter(month == 2) %>%
    group_by(year) %>% 
    summarize(atl.number = sum(count))
atl.gad.numbers <- left_join(fit.numbers, had.numbers)

had.numbers.plot <- 
    ggplot(data=atl.gad.numbers, aes(x=year)) + 
    geom_line(aes(y=ann.number, color='Gadget')) +
    geom_line(aes(y=atl.number, color='Atlantis')) +
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Numbers')

atl.age.numbers <- 
    is_fg_count %>%
    filter(month == 1) %>%
    group_by(year, age) %>%
    summarize(atl.number = sum(count))

age.numbers.plot <- 
    ggplot(data=age.numbers, aes(x=year, y=ann.number, color='Gadget')) + geom_line() +
    geom_line(data=atl.age.numbers, aes(x=year, y=atl.number, color='Atlantis')) +
    facet_wrap(~age) +
    scale_color_manual('', breaks=c('Gadget', 'Atlantis'), values=c('red', 'black')) +
    theme_bw() + xlab('Year') + ylab('Numbers')
```

## Biomass Across Time
```{r, biomass plot}
atl.gad.ts + ylim(0, 1.25e+09)
```

## Numbers Across Time
```{r, numbers plot}
had.numbers.plot
```

## Numbers by Age Across Time
```{r, numbers by age plot}
age.numbers.plot
```





