---
title:  "Gadget-Gadget Comparison"
author: "Paul Frater"
date:   ""
output: html_document
---
```{r global_options, include=F}
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=F, warning=F, message=F)
knitr::opts_knit$set(root.dir = '~/gadget/models/gadgetTest/zbraVersions/zbraVer3')
```

# Gadget-Atlantis Cod Comparison

```{r, gadget results, include=F}
library(plyr)
library(dplyr)
library(ggplot2)
library(grid)
library(Rgadget)
fit <- gadget.fit(wgts="WGTS", main.file='WGTS/main.final',
                  fleet.predict = data.frame(fleet = 'comm', ratio=1),
                  mat.par=c(-6.510198, 1.108594),
                  printfile.printatstart = 0,
                  printfile.steps = 1)
```

<!-- Add specific results/figures you want presented here-->

## Likelihoood
```{r}
    ggplot(filter(fit$likelihoodsummary, year != 'all'),
           aes(as.numeric(year), likelihood.value)) +
    geom_point() + facet_wrap(~component) +theme_bw()+
    xlab('Year') + ylab('Score')
```


```{r}
resTable <- fit$resTable[tail(head(names(fit$resTable),-2),-1)]

## to calculate biomass index
tmp <- mutate(fit$sidat, survey = ifelse(substr(name,1,3)=='aut','aut', 'igfs'))
tmp <- rbind.fill(tmp,
                  ddply(tmp,~year+survey, summarise,
                        number.x = sum(number.x*0.008249352*lower^3.026918 ),
                        predict = sum(predict*0.008249352*lower^3.026918 ),
                        upper = sum(upper*0.008249352*lower^3.026918 ),
                        lower = sum(lower*0.008249352*lower^3.026918 ),
                        length = 'Biomass'))

```

## Survey Indices
### For Spring
```{r}
    ggplot(subset(tmp, survey=='igfs'), aes(year,number.x)) +
    geom_point() +
    geom_line(aes(year,predict)) +
    geom_linerange(data=subset(tmp,year==max(year)),
                   aes(year,ymax=number.x,ymin=predict),col='green')+
    geom_text(data=mutate(subset(tmp,year==min(year)),y=Inf),
              aes(year,y,label=length), vjust = 2,hjust = -1)+
    facet_wrap(~length,scale='free_y',ncol=2) + theme_bw() +
    ylab('Index') + xlab('Year') +
    theme (panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

### and Autumn
``` {r}
    ggplot(subset(tmp, survey=='aut'), aes(year,number.x)) +
    geom_point() +
    geom_line(aes(year,predict)) +
    geom_linerange(data=subset(tmp,year==max(year)),
                   aes(year,ymax=number.x,ymin=predict),col='green')+
    geom_text(data=mutate(subset(tmp,year==min(year)),y=Inf),
              aes(year,y,label=length), vjust = 2,hjust = -1)+
    facet_wrap(~length,scale='free_y',ncol=2) + theme_bw() +
    ylab('Index') + xlab('Year') +
    theme (panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

## Length Distributions
### For Spring Surveys
```{r}
    ggplot(subset(fit$catchdist.fleets,name == 'ldist.spr') ,
           aes(lower,predicted)) + geom_line() +
    geom_line(aes(lower,observed),col='gray') +
    facet_wrap(~year+step) + theme_bw() + 
    geom_text(data=mutate(subset(fit$catchdist.fleets,
                                 name == 'ldist.igfs' & lower==min(lower)),y=Inf),
              aes(lower,y,label=year), vjust = 2,hjust = -1)+
    ylab('Proportion') + xlab('length') +
    theme (axis.text.y = element_blank(), axis.ticks.y = element_blank(),
           panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

### and Autumn Surveys
``` {r}
    ggplot(subset(fit$catchdist.fleets,name == 'ldist.aut') ,
           aes(lower,predicted)) + geom_line() +
    geom_line(aes(lower,observed),col='gray') +
    facet_wrap(~year+step) + theme_bw() + 
    geom_text(data=mutate(subset(fit$catchdist.fleets,
                                 name == 'ldist.aut' & lower==min(lower)),y=Inf),
              aes(lower,y,label=year), vjust = 2,hjust = -1)+
    ylab('Proportion') + xlab('length') +
    theme (axis.text.y = element_blank(), axis.ticks.y = element_blank(),
           panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

### And for the catch
``` {r}
    ggplot(subset(fit$catchdist.fleets,name == 'ldist.comm'),
           aes(lower,predicted)) +
    geom_line(aes(lower,observed),col='gray') +
    facet_wrap(~year+step) + theme_bw() + geom_line() +
    geom_text(data=mutate(subset(fit$catchdist.fleets,
                                 name == 'ldist.comm' & lower==min(lower)),y=Inf),
              aes(lower,y,label=year), vjust = 2,hjust = -1)+
    ylab('Proportion') + xlab('length') +
    theme (axis.text.y = element_blank(), axis.ticks.y = element_blank(),
           panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

## Age Distributions
### spring
``` {r}
dat <- fit$catchdist.fleets %>% group_by(name, year, step, age) %>%
    summarize(predicted=sum(predicted), 
              observed=sum(observed, na.rm=T)) %>%
    ungroup() %>% mutate(age = as.numeric(gsub('age', '', age)))
ggplot(data=filter(dat, name=='aldist.spr'), 
       aes(x=age, y=predicted)) + 
    geom_line(data=filter(dat, name=='aldist.spr'), 
              aes(x=age, y=observed), color='gray') +
    geom_line() + facet_wrap(~year+step) + theme_bw() +
    geom_text(data = mutate(filter(dat, name=='aldist.spr', 
                                   age==min(age, na.rm=T)), y = Inf), 
              aes(age, y, label = year), vjust = 2, hjust = -1) +
    theme(axis.text.y = element_blank(), 
          axis.ticks.y = element_blank(), 
          panel.margin = unit(0, "cm"), 
          plot.margin = unit(c(0, 0, 0, 0), "cm"), 
          strip.background = element_blank(), 
          strip.text.x = element_blank())
```

### Autumn Surveys
``` {r}
ggplot(data=filter(dat, name=='aldist.aut'), 
       aes(x=age, y=predicted)) + 
    geom_line(data=filter(dat, name=='aldist.aut'), 
              aes(x=age, y=observed), color='gray') +
    geom_line() + facet_wrap(~year+step) + theme_bw() +
    xlab('Age') + ylab('Proportion') +
    geom_text(data = mutate(filter(dat, name=='aldist.aut', 
                                   age==min(age, na.rm=T)), y = Inf), 
              aes(age, y, label = year), vjust = 2, hjust = -1) +
    theme(axis.text.y = element_blank(), 
          axis.ticks.y = element_blank(), 
          panel.margin = unit(0, "cm"), 
          plot.margin = unit(c(0, 0, 0, 0), "cm"), 
          strip.background = element_blank(), 
          strip.text.x = element_blank())
```

### Bottom Trawl Fleet
``` {r}
ggplot(data=filter(dat, name=='aldist.comm'), 
       aes(x=age, y=predicted)) + 
    geom_line(data=filter(dat, name=='aldist.comm'), 
              aes(x=age, y=observed), color='gray') +
    geom_line() + facet_wrap(~year + step) + theme_bw() +
    xlab('Age') + ylab('Proportion') +
    geom_text(data = mutate(filter(dat, name=='aldist.comm', 
                                   age==min(age, na.rm=T)), y = Inf), 
              aes(age, y, label = year), vjust = 2, hjust = -1) +
    theme(axis.text.y = element_blank(), 
          axis.ticks.y = element_blank(), 
          panel.margin = unit(0, "cm"), 
          plot.margin = unit(c(0, 0, 0, 0), "cm"), 
          strip.background = element_blank(), 
          strip.text.x = element_blank())
```


## Suitability
``` {r}
    ggplot(fit$suitability,
           aes(l,suit,lty=fleet)) +
    geom_line() +
    theme_bw() + ylab('Suitability') + xlab('Length') +
    theme(legend.position = c(0.8,0.25), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm')) 
```

## Growth
``` {r}
    ggplot(fit$stock.growth,
           aes(age,length)) + 
    geom_line() +
    theme_bw() + ylab('Length') + xlab('Age') +
    theme(legend.position = c(0.9,0.75), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```

## Recruitment
``` {r}
    ggplot(fit$res.by.year, aes(year,recruitment/1e6)) +
    geom_bar(stat='identity') +
    ylab("Recruitment (in millions)") + xlab('Year') +  theme_bw() +
    theme(legend.position = c(0.25,0.75), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```

## Landings By Year
``` {r}
ggplot(fit$res.by.year,aes(year,catch/1000)) +
    geom_bar(stat='identity') +
    ylab("Catches (in tons)") + xlab('Year') +  theme_bw() +
    theme(legend.position = c(0.25,0.75), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```

## Biomass
Overall
``` {r}
    ggplot(fit$res.by.year, 
           aes(year,total.biomass/1000)) +
    geom_bar(stat='identity') +
    ylab("Total biomass (in tons)") + xlab('Year') +  theme_bw() +
    theme(legend.position = c(0.25,0.75), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```

Harvestable Biomass
``` {r}
    ggplot(fit$res.by.year,
           aes(year,harv.biomass/1000)) +
    geom_bar(stat='identity') +
    ylab("Harvestable biomass (in tons)") + xlab('Year') +  theme_bw()
```

SSB
``` {r}
    ggplot(fit$res.by.year,
           aes(year,ssb/1000)) +
    geom_bar(stat='identity') +
    ylab("SSB (in tons)") + xlab('Year') +  theme_bw() +
    theme(legend.position = c(0.4, 0.8), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```

## F
``` {r}
   ggplot(fit$res.by.year, aes(year, F)) + 
    geom_line() + 
    ylab("F") + xlab("Year") +  theme_bw() +
    theme(legend.position=c(0.2, 0.8), legend.title = element_blank(),
          plot.margin = unit(c(0,0,0,0),'cm'))
```
