---
title:  "GSS Model"
author: "Paul Frater"
date:   ""
output: html_document
---
```{r global_options, include=F}
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=F, warning=F, message=F)
knitr::opts_knit$set(root.dir = '~/gadget/gadget-models/grSilverSmelt/gssModel')
```

# Gadget Model for greater silver smelt

```{r, gadget results, include=F}
library(plyr)
library(dplyr)
library(ggplot2)
library(grid)
library(Rgadget)
setwd('~/gadget/gadget-models/grSilverSmelt/gssModel')
fit <- gadget.fit(wgts="WGTS", main.file='WGTS/main.final',
                  fleet.predict = data.frame(fleet = 'bmt.comm', ratio=1),
                  mat.par=c(-7.9997960, 0.2001406))
```

<!-- Add specific results/figures you want presented here-->

```{r}
    ggplot(filter(fit$likelihoodsummary, year != 'all'),
           aes(as.numeric(year), likelihood.value)) +
    geom_point() + facet_wrap(~component, scales="free_y") +theme_bw()+
    xlab('Year') + ylab('Score')
```

```{r}
tmp <- mutate(fit$sidat, survey = ifelse(substr(name,1,3)=='aut','aut', 'igfs'))
tmp <- rbind.fill(tmp,
                  ddply(tmp,~year+survey, summarise,
                        number.x = sum(number.x*0.000003129303*lower^3.224769 ),
                        predict = sum(predict*0.000003129303*lower^3.224769 ),
                        upper = sum(upper*0.000003129303*lower^3.224769 ),
                        lower = sum(lower*0.000003129303*lower^3.224769 ),
                        length = 'Biomass'))
```

```{r}
    ggplot(subset(tmp, survey=='igfs'), aes(year,number.x)) +
    geom_point() +
    geom_line(aes(year,predict)) +
    geom_linerange(data=subset(tmp,year==max(year)),
                   aes(year,ymax=number.x,ymin=predict),col='green')+
    geom_text(data=mutate(subset(tmp,year==min(year)),y=Inf),
              aes(year,y,label=length), vjust = 2,hjust = -1)+
    facet_wrap(~length,scale='free_y',ncol=2) + theme_bw() +
    ylab('Index') + xlab('Year') +
    theme (panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())

    ggplot(filter(tmp, survey=='aut'), aes(year,number.x)) +
    geom_point() +
    geom_line(aes(year,predict)) +
    geom_linerange(data=subset(tmp,year==max(year)),
                   aes(year,ymax=number.x,ymin=predict),col='green')+
    geom_text(data=mutate(subset(tmp,year==min(year)),y=Inf),
              aes(year,y,label=length), vjust = 2,hjust = -1)+
    facet_wrap(~length,scale='free_y',ncol=2) + theme_bw() +
    ylab('Index') + xlab('Year') +
    theme (panel.margin = unit(0,'cm'), plot.margin = unit(c(0,0,0,0),'cm'),
           strip.background = element_blank(), strip.text.x = element_blank())
```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```

``` {r}

```


