gadgetlikelihood('likelihood', gd$dir, missingOkay=T) %>%
    gadget_update('penalty',
                  name = "bounds",
                  weight = "0.5",
                  data = data.frame(
                      switch = c("default"),
                      power = c(2),
                      upperW=10000,
                      lowerW=10000,
                      stringsAsFactors = FALSE)) %>%
    gadget_update('understocking',
                  name = 'understocking',
                  weight = '100') %>%
    # gadget_update('surveydistribution',
    #               name = 'ldist.spr',
    #               weight = 1,
    #               data = ldist.igfs[[1]],
    #               parameters = c(0.001, 0),
    #               # parameters = quote(exp(spr.si.beta) * 0.7072256) %>%
    #               #              to.gadget.formulae(),
    #               suitability = surveydist_suit(stock = stocknames,
    #                                           fun = 'constant',
    #                                           params = 1),
    #               stocknames = stocknames) %>%
    # gadget_update('surveydistribution',
    #               name = 'aldist.spr',
    #               weight = 1,
    #               data = aldist.igfs[[1]],
    #               parameters = c(0.001, 0),
    #               # parameters = quote(exp(spr.si.beta) * 0.0707215) %>%
    #               #              to.gadget.formulae(),
    #               suitability = surveydist_suit(stock = stocknames,
    #                                           fun = 'constant',
    #                                           params = 1),
    #               stocknames = stocknames) %>%
    # gadget_update('surveydistribution',
    #               name = 'ldist.aut',
    #               weight = 1,
    #               data = ldist.aut[[1]],
    #               parameters = c(0.001, 0),
    #               # parameters = quote(exp(aut.si.beta) * 0.7072256) %>%
    #               #              to.gadget.formulae(),
    #               suitability = surveydist_suit(stock = stocknames,
    #                                           fun = 'constant',
    #                                           params = 1),
    #               stocknames = stocknames) %>%
    # gadget_update('surveydistribution',
    #               name = 'aldist.aut',
    #               weight = 1,
    #               data = aldist.aut[[1]],
    #               parameters = c(0.001, 0),
    #               # parameters = quote(exp(aut.si.beta) * 0.0707215) %>%
    #               #              to.gadget.formulae(),
    #               suitability = surveydist_suit(stock = stocknames,
    #                                           fun = 'constant',
    #                                           params = 1),
    #               stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.spr',
                  weight = 1,
                  data = ldist.igfs[[1]],
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.spr',
                  weight = 1,
                  data = aldist.igfs[[1]],
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.aut',
                  weight = 1,
                  data = ldist.aut[[1]],
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.aut',
                  weight = 1,
                  data = aldist.aut[[1]],
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.comm',
                  weight = 1,
                  data = ldist.comm[[1]],
                  fleetnames = c('comm'),
                  stocknames = stock) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.comm',
                  weight = 1,
                  data = aldist.comm[[1]],
                  fleetnames = c('comm'),
                  stocknames = stock) %>%
    # gadget_update('catchdistribution',
    #               name = 'ldist.discards',
    #               weight = 1,
    #               data = ldist.discards[[1]],
    #               fleetnames = c('discards'),
    #               stocknames = stocknames) %>%
    # gadget_update('catchdistribution',
    #               name = 'aldist.discards',
    #               weight = 1,
    #               data = aldist.discards[[1]],
    #               fleetnames = c('discards'),
    #               stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.0.18',
                  weight = 1,
                  data = spr.si.0.18[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.18.33',
                  weight = 1,
                  data = spr.si.18.33[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.33.45',
                  weight = 1,
                  data = spr.si.33.45[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.45.58',
                  weight = 1,
                  data = spr.si.45.58[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.58.80',
                  weight = 1,
                  data = spr.si.58.80[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = c(stock)) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.80.pl',
                  weight = 1,
                  data = spr.si.80.pl[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = c(stock)) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.0.18',
                  weight = 1,
                  data = aut.si.0.18[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.18.33',
                  weight = 1,
                  data = aut.si.18.33[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.33.45',
                  weight = 1,
                  data = aut.si.33.45[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.45.58',
                  weight = 1,
                  data = aut.si.45.58[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.58.80',
                  weight = 1,
                  data = aut.si.58.80[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = c(stock)) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.80.pl',
                  weight = 1,
                  data = aut.si.80.pl[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = c(stock)) %>%
    write.gadget.file(gd$dir)
